//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShahWilayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileManagement
    {
        public int FileManagementId { get; set; }
        public string ContentName { get; set; }
        public string FilePath { get; set; }
        public int IsParent { get; set; }
        public int ParentId { get; set; }
        public int IsSubParent { get; set; }
        public int IsSubChild { get; set; }
        public int ParentOrder { get; set; }
        public int SubParentOrder { get; set; }
        public int SubChildOrder { get; set; }
        public int IsChildHead { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
