//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShahWilayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Allotments = new HashSet<Allotment>();
            this.AssociateAllotments = new HashSet<AssociateAllotment>();
            this.AssociateMembers = new HashSet<AssociateMember>();
            this.CnicHistories = new HashSet<CnicHistory>();
            this.Installments = new HashSet<Installment>();
            this.Invoices = new HashSet<Invoice>();
            this.Nominees = new HashSet<Nominee>();
            this.PaymentPlans = new HashSet<PaymentPlan>();
            this.Payments = new HashSet<Payment>();
            this.SocietyPayments = new HashSet<SocietyPayment>();
            this.Transfers = new HashSet<Transfer>();
            this.TransferLogs = new HashSet<TransferLog>();
            this.AssociateTransfers = new HashSet<AssociateTransfer>();
        }
    
        public int MemberId { get; set; }
        public int TitleId { get; set; }
        public int MemberRelationId { get; set; }
        public int GenderId { get; set; }
        public int CountryId { get; set; }
        public int ProvinceId { get; set; }
        public int CityId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string CellNo { get; set; }
        public string Landline { get; set; }
        public string WhatsApp { get; set; }
        public string OfficePhone { get; set; }
        public string Email { get; set; }
        public System.DateTime Dob { get; set; }
        public string BirthPlace { get; set; }
        public string CNIC { get; set; }
        public System.DateTime CnicExpiryDate { get; set; }
        public string BloodGroup { get; set; }
        public string PostalCode { get; set; }
        public string PermanentAddress { get; set; }
        public string Occupation { get; set; }
        public string MembershipNo { get; set; }
        public System.DateTime MembershipDate { get; set; }
        public string ReferenceNo { get; set; }
        public string FolioNo { get; set; }
        public string CnicFrontFile { get; set; }
        public string CnicBackFile { get; set; }
        public string ProfileFile { get; set; }
        public bool IsMember { get; set; }
        public bool IsGone { get; set; }
        public Nullable<System.DateTime> GoneDate { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Allotment> Allotments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssociateAllotment> AssociateAllotments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssociateMember> AssociateMembers { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CnicHistory> CnicHistories { get; set; }
        public virtual Country Country { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Installment> Installments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual MemberRelation MemberRelation { get; set; }
        public virtual MemberRelation MemberRelation1 { get; set; }
        public virtual Member Members1 { get; set; }
        public virtual Member Member1 { get; set; }
        public virtual Province Province { get; set; }
        public virtual Title Title { get; set; }
        public virtual Title Title1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nominee> Nominees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentPlan> PaymentPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SocietyPayment> SocietyPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer> Transfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferLog> TransferLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssociateTransfer> AssociateTransfers { get; set; }
    }
}
