//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShahWilayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuItem()
        {
            this.RoleMenuMappings = new HashSet<RoleMenuMapping>();
        }
    
        public int MenuItemId { get; set; }
        public string MenuItemName { get; set; }
        public string MenuItemURL { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> IsParent { get; set; }
        public bool IsActive { get; set; }
        public string Icon { get; set; }
        public Nullable<int> MenuOrder { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleMenuMapping> RoleMenuMappings { get; set; }
    }
}
