//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShahWilayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nominee
    {
        public int NomineeId { get; set; }
        public int MemberId { get; set; }
        public int TitleId { get; set; }
        public int MemberRelationId { get; set; }
        public int RelationId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public System.DateTime Dob { get; set; }
        public string BirthPlace { get; set; }
        public string CNIC { get; set; }
        public string CellNo { get; set; }
        public string Address { get; set; }
        public string CnicFront { get; set; }
        public string CnicBack { get; set; }
        public string ProfileFile { get; set; }
        public string BirthCertificate { get; set; }
        public string FrcFile { get; set; }
        public string HereshipCertificate { get; set; }
        public string GuardianCertificate { get; set; }
        public string DeathCertificate { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual MemberRelation MemberRelation { get; set; }
        public virtual Member Member { get; set; }
        public virtual Relation Relation { get; set; }
        public virtual Title Title { get; set; }
    }
}
