//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShahWilayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentSetup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentSetup()
        {
            this.Charges = new HashSet<Charge>();
        }
    
        public int PaymentSetupId { get; set; }
        public int TenureId { get; set; }
        public int PlotTypeId { get; set; }
        public double Rate { get; set; }
        public int PlotId { get; set; }
        public bool IsFixed { get; set; }
        public bool HasSizeBase { get; set; }
        public int SizeFrom { get; set; }
        public int SizeTo { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Charge> Charges { get; set; }
        public virtual PlotType PlotType { get; set; }
        public virtual Tenure Tenure { get; set; }
    }
}
