//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShahWilayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentPlan
    {
        public int PaymentPlanId { get; set; }
        public int ChargeId { get; set; }
        public int InstallmentPlanId { get; set; }
        public int MemberId { get; set; }
        public int PlotId { get; set; }
        public int DueDay { get; set; }
        public int Surcharge { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Charge Charge { get; set; }
        public virtual InstallmentPlan InstallmentPlan { get; set; }
        public virtual Member Member { get; set; }
        public virtual Plot Plot { get; set; }
    }
}
