//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShahWilayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int PaymentDetailId { get; set; }
        public int PaymentId { get; set; }
        public long Balance { get; set; }
        public int InstallmentPlan { get; set; }
        public long InstallmentAmount { get; set; }
        public int Surcharge { get; set; }
        public long SurchargeAmount { get; set; }
        public long TotalAmount { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public decimal PaidPercent { get; set; }
        public decimal RemainingPercent { get; set; }
        public bool HasPaymentPlan { get; set; }
        public bool HasOverDue { get; set; }
        public int CategoryPercent { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
