//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShahWilayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocietyPaymentDetail
    {
        public int SocietyPaymentDetailId { get; set; }
        public int SocietyPaymentId { get; set; }
        public int TenureId { get; set; }
        public int Rate { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public Nullable<double> PaidPercent { get; set; }
        public Nullable<double> RemainingPercent { get; set; }
        public Nullable<int> CategoryPercent { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual SocietyPayment SocietyPayment { get; set; }
        public virtual Tenure Tenure { get; set; }
    }
}
