//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShahWilayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTable
    {
        public int TempTableId { get; set; }
        public int MemberId { get; set; }
        public int PlotId { get; set; }
        public string PlotNo { get; set; }
    }
}
