//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShahWilayat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transfer()
        {
            this.TransferLogs = new HashSet<TransferLog>();
        }
    
        public int TransferId { get; set; }
        public int PlotId { get; set; }
        public int MemberId { get; set; }
        public string TransferOrderNo { get; set; }
        public System.DateTime TransferDate { get; set; }
        public Nullable<System.DateTime> MCMDate { get; set; }
        public bool IsTransfered { get; set; }
        public Nullable<System.DateTime> NewspaperAdvDate { get; set; }
        public string NewspaperName { get; set; }
        public string NewspaperScan { get; set; }
        public string IndemnityBondScan { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string TransferOrderScan { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Plot Plot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferLog> TransferLogs { get; set; }
    }
}
